name: Gradle CI

on: push

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - run: chmod +x ./gradlew
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Test with Gradle
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      with:
        arguments: check
