name: Release

on:
  push:
    tags:
      - "v*.*.*"
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - run: chmod +x ./gradlew

      - name: Build
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: build

      - name: Pack shadow artifact
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: shadowjar

      - name: Generate release changelog
        run: |
          echo "# Changes" > commits.md
          git log --pretty=format:"* \`%h\` %s" $(git describe --tags --abbrev=0 @^)..@ >> commits.md
          cat commits.md

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          body_path: commits.md
          files: |
            build/libs/*
