name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - "v*.*.*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Gradlew Permission Workaround
      run: chmod +x ./gradlew
    - name: Build
      run: ./gradlew build
    - name: Pack shadow artifact
      run: ./gradlew shadowjar
    - name: Generate release changelog
      uses: heinrichreimer/github-changelog-generator-action@v2.3
      with:
        token: ${{ secrets.GH_TOKEN }} 
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        body_path: CHANGELOG.md
        files: |
          build/libs/*
